site_name: Offboard Studio
site_url: https://offboard-studio.github.io/webots-simulink
site_description: AI powered Robotics and Computer Vision Workflow Automation IDE
site_author: Offboard Studio

nav:
  - Home: index.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Contributors: contributors.md
  - References: references.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo.png
  # favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - def_list
  - fenced_code
  - footnotes
  - tables
  - toc:
      permalink: true
      permalink_class: headerlink
      permalink_title: Permalink
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist

extra:
  social:
    # - icon: simple/youtube
    #   link: https://youtube.com/@harunkurtdev
    # - icon: simple/linkedin
    #   link: https://linkedin.com/in/

copyright: Copyright &copy; 2025 offboardstudio